
baseurl = "http://www.anshulpatel.in/"
title = "Anshul Patel"
theme = "hugo-theme-nix"
languageCode = "en-us"
author = "Anshul Patel"

[menu]
  [[menu.header]]
    name = "blog"
    weight = 1
    url = "/post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "meetups"
    weight = 1
    url = "/meetup"
  # [[menu.header]]
  #   name = "geeky"
  #   weight = 0
  #   url = "http://anveshak-anveshak.193b.starter-ca-central-1.openshiftapps.com"

[params]
  GithubID = "anshulpatel25"
  SlideShareID = "anshulpatel5"
  SteamID = "anveshak25"
  DzoneID = "anshulp25"
  WhatsappID = "+918390905963"
  PhoneID = "+918390905963"
  SkypeID = "anshul.patel32"
  StackOverflowID = "78211"
  LinkedInID = "anshul-patel-29a95635"
  Name = "Anshul Patel"
  TagLine = "Geek, Gamer, Techie"
  HeaderUsername = "anshul"
  HeaderHostname = "patel"
  Email = "anshulpatel25@gmail.com"
  GitlabID = "anshulpatel25"
  ProfilePicture = "/anshul_infostretch.jpg"
  GoogleAnalytics = "UA-93926186-1"
