baseurl = "http://example.org/"
title = "Anshul Patel"
theme = "hugo-theme-nix"
languageCode = "en-us"
author = "Anshul Patel"

[menu]
  [[menu.header]]
    name = "post"
    weight = 0
    url = "/post"
  [[menu.header]]
    name = "about"
    weight = 1
    url = "/about"
  [[menu.header]]
    name = "geeky"
    weight = 2
    url = "http://geeky.anshulpatel.in"

[params]
  GithubID = "your_github"
  SlideShareID = "your_slideshare"
  SteamID = "your_steam"
  DzoneID = "your_dzone"
  WhatsappID = "your_whatsapp"
  PhoneID = "your_phone"
  SkypeID = "your_skype"
  TwitterID = "your_twitter"
  StackOverflowID = "your_stackoverflow"
  LinkedInID = "your_linkedin"
  Name = "Anshul Patel"
  HeaderUsername = "anshul"
  HeaderHostname = "patel"
  Email = "your_email"
  About = "Knowledge is neither good nor bad, morality lies in its application."
  ProfilePicture = "/profile.jpg"
